[package]
name = "mess-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mess-api-derive = { path = "derive", optional = true }

[features]
derive = [
    "mess-api-derive"
]